### ISSUE TITLE
Sample code for visualization

### ISSUE THREAD

**Issue by taesiri** [ollenilsson19/PGA-MAP-Elites#3]
Hello, 

First of all, Thank you for your fantastic work and also for sharing the code.

I was wondering if it is possible to share the code for visualizing the archive of policies like in the paper. I am performing some experiments with different configurations and want to reproduce the results from the paper. So far, even after 1 million evaluation steps, all of the disvoered policies are extremely similar. 

Thank you.

**Comment by ollebompa** [comment]
Hi,

For plotting the archives we use code based on the pymap_elites framework, so check that out: https://github.com/resibots/pymap_elites/blob/master/plot/plot_2d_map.py

**Comment by Kaito-Kido** [comment]
Hi,

I can run the code on Google Colab but this error appear when I run on my machine. Help me please.

Thank for your help.
![image](https://user-images.githubusercontent.com/62087110/165687881-886950f1-9b98-449e-aa3e-039368e912dd.png)

**Comment by ollebompa** [comment]
Hi,

It is explained in the README how to fix this. It has nothing to do with your code but rather your OS:

If you get "Too many open files" errors, this has to do with limitations imposed by your OS and is not an error related to the code. Depending on your system, this may be solved by:

`ulimit -n 4000`
